// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXVaUsupsNN_CKsGl0bpjcwlpZgTVP6Ws',
    appId: '1:488977322120:web:b8fdf05bd83615fc2d0f3d',
    messagingSenderId: '488977322120',
    projectId: 'blender-364018',
    authDomain: 'blender-364018.firebaseapp.com',
    storageBucket: 'blender-364018.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxLXUXPvUMZ9nrU_DFaqdpd__9GRGHKio',
    appId: '1:488977322120:android:15892a4abe40acdc2d0f3d',
    messagingSenderId: '488977322120',
    projectId: 'blender-364018',
    storageBucket: 'blender-364018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyEMOTCl_Rk3zlgibN4qawnape7gWzyy8',
    appId: '1:488977322120:ios:e19d9b8f66325f3d2d0f3d',
    messagingSenderId: '488977322120',
    projectId: 'blender-364018',
    storageBucket: 'blender-364018.appspot.com',
    androidClientId: '488977322120-9qeo7pcjac2qhhv6j8kchq4aqp57chq0.apps.googleusercontent.com',
    iosClientId: '488977322120-ivfn2k1t3d5lbsueeavh94pnpe2r5mog.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyEMOTCl_Rk3zlgibN4qawnape7gWzyy8',
    appId: '1:488977322120:ios:2f7be026f4d20a392d0f3d',
    messagingSenderId: '488977322120',
    projectId: 'blender-364018',
    storageBucket: 'blender-364018.appspot.com',
    androidClientId: '488977322120-9qeo7pcjac2qhhv6j8kchq4aqp57chq0.apps.googleusercontent.com',
    iosClientId: '488977322120-7096qldkbh4qsd2730bdbsv028ndiqgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
