version: 2.1

executors:
  container-executor:
    docker:
      - image: mongo:5.0.18
        environment:
          ENVIRONMENT: development
          JWT_SECRET: BA2F2F9F-9F9F-4F2B-BA2F-2F9F9F4F2BBA
    working_directory: ~/yellyoshua

commands:
  install-packages:
    steps:
      - run: |
          apt-get update -y
          apt-get install -y curl \
          nano software-properties-common \
          git wget tar build-essential \
          libssl-dev libffi-dev -y

  install-node:
    steps:
      - run: curl -sL https://deb.nodesource.com/setup_18.x | bash
      - run: apt-get install -y nodejs

  install-gcloud:
    steps:
      - run: 
          name: Install gcloud
          command: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            apt-get update -yq
            apt-get install google-cloud-sdk -yq
            apt-get install google-cloud-sdk-gke-gcloud-auth-plugin -yq

  install-docker:
    steps:
      - run: 
          name: Install docker
          command: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
            apt-get update -yq
            apt-get install docker-ce -yq

  activate-service-account:
    steps:
      - run: 
          name: Activate service account
          command: |
            echo $GCLOUD_SERVICE_KEY_CI | base64 --decode --ignore-garbage > ~/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
            gcloud auth configure-docker --quiet

  # install-playwright:
  #   steps:
  #     - run: npx playwright install-deps

  build-image:
    steps:
      - activate-service-account
      - run: |
          docker ps -a
          docker build -t us.gcr.io/${GCP_PROJECT_ID}/weblend/${CONTAINER}:latest ./infraestructure/docker/${CONTAINER_FILE}
          docker push us.gcr.io/${GCP_PROJECT_ID}/weblend/${CONTAINER}:latest
  
  test-client:
    steps:
      - run: cd client && echo "Testing client"
  
  test-server:
    steps:
      - run: cd server && npm install --save-dev
      - run: cd server && npm run test

  reset-development-seed:
    steps:
      - run: cd server && npm install --save-dev
      - run: cd server && npm run seed

jobs:
  server-test:
    executor: container-executor
    steps:
      - install-packages
      - install-node
      - checkout
      - setup_remote_docker
      - run: mongod --fork --logpath /var/log/mongod.log
      - test-server
  
  development-seed:
    executor: container-executor
    steps:
      - install-packages
      - install-node
      - checkout
      - setup_remote_docker
      - reset-development-seed
  
  development-server:
    executor: container-executor
    environment:
      CONTAINER: server-development
      CONTAINER_FILE: Server.Dockerfile
    steps:
      - install-packages
      - install-node
      - install-gcloud
      - install-docker
      - checkout
      - setup_remote_docker
      - build-image

  check-branch:
    executor: container-executor
    resource_class: large
    steps:
      - run: echo "Checking branch"

workflows:
  version: 2
  development:
    jobs:
      - check-branch:
          filters:
            branches:
              only:
                - development
      - server-test:
          requires:
            - check-branch
      - development-server:
          requires:
            - check-branch
      - development-seed:
          requires:
            - development-server