---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "weblend-production"
  namespace: "default"
  labels:
    app: "weblend-production"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "weblend-production"
  template:
    metadata:
      labels:
        app: "weblend-production"
    spec:
      containers:
      - name: "weblend-production"
        image: "us.gcr.io/blender-364018/weblend/server-production:latest"
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: "production"
          - name: PORT
            value: "3000"
          - name: FRONTEND_URL
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: FRONTEND_URL
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: DATABASE_URL
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: JWT_SECRET
          - name: APP_GOOGLE_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: APP_GOOGLE_REDIRECT_URI
          - name: APP_GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: APP_GOOGLE_CLIENT_SECRET
          - name: APP_GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: APP_GOOGLE_CLIENT_ID
          - name: GOOGLE_MAPS_API_KEY
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: GOOGLE_MAPS_API_KEY
          - name: AWS_SERVER_BUCKET
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: AWS_SERVER_BUCKET
          - name: AWS_SERVER_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: AWS_SERVER_SECRET_ACCESS_KEY
          - name: AWS_SERVER_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: AWS_SERVER_ACCESS_KEY_ID
          - name: AWS_SERVER_REGION
            valueFrom:
              secretKeyRef:
                name: weblend-production-config
                key: AWS_SERVER_REGION
        resources:
          requests:
            cpu: 100m
            ephemeral-storage: 200Mi
            memory: 128Mi
          limits:
            cpu: 200m
            ephemeral-storage: 200Mi
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: "/api/health"
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5